-- AI Detective K — Database Initialization
--
-- Schema is managed by Alembic migrations (backend/alembic/versions/).
-- This file intentionally contains no DDL so that Alembic is the single
-- source of truth.  Postgres runs this script only on the very first
-- container start (empty data dir); subsequent starts skip it entirely.
--
-- To apply the schema:
--   docker-compose exec backend alembic upgrade head
--
-- To reset everything:
--   docker-compose down -v && docker-compose up
